package com.xdev.rcmigrationexample.ui.gencols;

import com.flowingcode.vaadin.addons.ironicons.ImageIcons;
import com.rapidclipse.framework.server.data.renderer.RenderedComponent;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.xdev.rcmigrationexample.domain.Product;

public class GenColProduct extends HorizontalLayout implements RenderedComponent<Product>
{

	/**
	 * 
	 */
	public GenColProduct()
	{
		super();
		this.initUI();
	}

	@Override
	public void renderComponent(Product value)
	{
		// TODO Auto-generated method stub
		
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #button4}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button4_onClick(final ClickEvent<Button> event)
	{
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.button2 = new Button();
		this.button  = new Button();
		this.button3 = new Button();
		this.button4 = new Button();
		
		this.button2.setText("Edit");
		this.button2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
		this.button2.setIcon(ImageIcons.EDIT.create());
		this.button.setText("Button");
		this.button.addThemeVariants(ButtonVariant.LUMO_PRIMARY, ButtonVariant.LUMO_ERROR);
		this.button.setIcon(VaadinIcon.TRASH.create());
		this.button3.setText("Button");
		this.button4.setClassName("multiline-button");
		this.button4.setText("Ich bin ein langer Text");
		
		this.button2.setSizeUndefined();
		this.button.setSizeUndefined();
		this.button3.setSizeUndefined();
		this.button4.setWidth("100px");
		this.button4.setHeight(null);
		this.add(this.button2, this.button, this.button3, this.button4);
		this.setSizeUndefined();
		
		this.button4.addClickListener(this::button4_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private Button button2, button, button3, button4;
	// </generated-code>
	
}
